admin_credentials: XRDSST_ADMIN
security_server:
- name: ss-mj
  url: https://127.0.0.1:1000/api/v1
  api_key_url: https://127.0.0.1:1000/api/v1/api-keys
  api_key: SS_MJ_API_KEY
  configuration_anchor: ./xroad/anchors/TL-TEST-anchor.xml
  software_token_id: 0
  software_token_pin: TOKEN_PIN
  owner_member_class: GOV
  owner_member_code: MJ
  owner_dn_country: TL
  owner_dn_org: Ministry of Justice
  profile: FI
  security_server_code: ss-mj
  fqdn: ss-mj
  clients:
  - member_class: GOV
    member_code: MJ
    member_name: Ministry of Justice
    subsystem_code: JUSTICE
    connection_type: HTTPS_NO_AUTH
    service_descriptions:
    - url: http://mj-mock:8080
      type: REST
      rest_service_code: birth-certificate
      access:
      - TL-TEST/GOV/OSS/PORTAL
- name: ss-serve
  url: https://127.0.0.1:2000/api/v1
  api_key_url: https://127.0.0.1:2000/api/v1/api-keys
  api_key: SS_SERVE_API_KEY
  configuration_anchor: ./xroad/anchors/TL-TEST-anchor.xml
  software_token_id: 0
  software_token_pin: TOKEN_PIN
  owner_member_class: GOV
  owner_member_code: SERVE
  owner_dn_country: TL
  owner_dn_org: SERVE I.P.
  profile: FI
  security_server_code: ss-serve
  fqdn: ss-serve
  clients:
  - member_class: GOV
    member_code: SERVE
    member_name: SERVE I.P.
    subsystem_code: REGISTRY
    connection_type: HTTPS_NO_AUTH
    service_descriptions:
    - url: http://serve-mock:8080
      type: REST
      rest_service_code: eKYB
      access:
      - TL-TEST/GOV/OSS/PORTAL
- name: ss-mtc
  url: https://127.0.0.1:3000/api/v1
  api_key_url: https://127.0.0.1:3000/api/v1/api-keys
  api_key: SS_MTC_API_KEY
  configuration_anchor: ./xroad/anchors/TL-TEST-anchor.xml
  software_token_id: 0
  software_token_pin: TOKEN_PIN
  owner_member_class: GOV
  owner_member_code: MTC
  owner_dn_country: TL
  owner_dn_org: Ministry of Transport and Communications
  profile: FI
  security_server_code: ss-mtc
  fqdn: ss-mtc
  clients:
  - member_class: GOV
    member_code: MTC
    member_name: Ministry of Transport and Communications
    subsystem_code: DNTT
    connection_type: HTTPS_NO_AUTH
    service_descriptions:
    - url: http://dntt-mock:8080
      type: REST
      rest_service_code: driver-license
      access:
      - TL-TEST/GOV/OSS/PORTAL
      - TL-TEST/GOV/MJ/JUSTICE
- name: ss-oss
  url: https://127.0.0.1:5000/api/v1
  api_key_url: https://127.0.0.1:5000/api/v1/api-keys
  api_key: SS_OSS_API_KEY
  configuration_anchor: ./xroad/anchors/TL-TEST-anchor.xml
  software_token_id: 0
  software_token_pin: TOKEN_PIN
  owner_member_class: GOV
  owner_member_code: OSS
  owner_dn_country: TL
  owner_dn_org: Balkaun Uniku
  profile: FI
  security_server_code: ss-oss
  fqdn: ss-oss
  clients:
  - member_class: GOV
    member_code: OSS
    member_name: Balkaun Uniku
    subsystem_code: PORTAL
    connection_type: HTTPS_NO_AUTH
